PUT  http://localhost:5000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDc3MjBiNjA5ZTYxMGY2NTM1ZGRmYSIsImlhdCI6MTc0OTY2NDk5MCwiZXhwIjoxNzUwMjY5NzkwfQ.sk5Q0if6UPG03A6_Wx3ia1Fdrd9ZIziUhqrhR4qaB5E
 
{  
}